services:
  gateway-service:
    build:
      context: ./apps/gateway-service1
      dockerfile: Dockerfile
    depends_on:
      - keycloak
    container_name: gateway-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080
      - NEXT_PUBLIC_KEYCLOAK_REALM=quiz-app
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=frontend
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080
      - USER_SERVICE_URL=http://user-service:3002
      - QUIZ_SERVICE_URL=http://quiz-service:3003
      - SESSION_SERVICE_URL=http://quiz-session-service:3004
      - DEBUG=keycloak-connect:* npm start
      - ADMIN_CLIENT_ID=admin-cli
      - ADMIN_CLIENT_SECRET_FILE=/run/secrets/gateway_admin_client_secret
    secrets:
      - gateway_keycloak_client_secret
      - gateway_session_secret
      - gateway_admin_username
      - gateway_admin_password
      - gateway_user_service_secret
      - gateway_admin_client_secret
    networks:
      - wordmaster-net
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-service:
    build:
      context: ./apps/frontend-service
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NEXTAUTH_URL=http://localhost:3000
      - KEYCLOAK_CLIENT_ID=frontend
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/quiz-app
      - NEXT_PUBLIC_GATEWAY_URL=http://gateway-service:3001
      - NEXT_PUBLIC_USER_API_URL=http://user-service:3002
    secrets:
      - frontend_nextauth_secret
    ports:
      - "3000:3000"
    networks:
      - app-net
      - wordmaster-net

  user-service:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://flapinski:cyckidupcia@postgres:5432/wordmaster
      - PRISMA_MIGRATION_SHADOW_DATABASE_URL="postgresql://flapinski:cyckidupcia@postgres:5432/shadowdb"
    depends_on:
      - postgres
    networks:
      - wordmaster-net
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: flapinski
      POSTGRES_PASSWORD: cyckidupcia
      POSTGRES_DB: wordmaster
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wordmaster-net

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: keycloakdb
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --hostname-strict=false
      - --hostname-url=http://localhost/auth
      - --hostname-admin-url=http://localhost/auth
      - --db=postgres
      - --db-url=jdbc:postgresql://keycloak-db:5432/keycloakdb
      - --db-username=keycloak
      - --db-password=securepassword
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    networks:
      - app-net
    volumes:
      - keycloak-data:/opt/keycloak/data

  # redis:
  #   image: redis:7
  #   container_name: wordmaster-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - wordmaster-net

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quizdb
    volumes:
      - mongo-data:/data/db
    networks:
      - wordmaster-net

  mongo-session:
    image: mongo:6
    container_name: mongo-session
    restart: always
    ports:
      - "29101:29101"
    environment:
      MONGO_INITDB_DATABASE: sessiondb
    volumes:
      - mongo-session-data:/data/db
    networks:
      - wordmaster-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
    networks:
      - app-net

  quiz-service:
    build:
      context: ./apps/quiz-service
      dockerfile: Dockerfile
    container_name: quiz-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    secrets:
      - quiz_mongo_uri
    depends_on:
      - mongo
    networks:
      - wordmaster-net
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  quiz-session-service:
    build:
      context: ./apps/quiz-session-service
      dockerfile: Dockerfile
    container_name: quiz-session-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    secrets:
      - quiz_session_mongo_uri
      - quiz_session_quiz_service_url
    depends_on:
      - mongo-session
    networks:
      - wordmaster-net
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  test-db:
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: quizzapp_test
    ports:
      - "5434:5432"

networks:
  wordmaster-net:
    driver: bridge
  app-net:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data:
  keycloak-db-data:
  user-db-data:
  mongo-data:
  mongo-session-data:

secrets:
  frontend_nextauth_secret:
    file: ./secrets/frontend_nextauth_secret
  gateway_keycloak_client_secret:
    file: ./secrets/gateway_keycloak_client_secret
  gateway_session_secret:
    file: ./secrets/gateway_session_secret
  gateway_admin_username:
    file: ./secrets/gateway_admin_username
  gateway_admin_password:
    file: ./secrets/gateway_admin_password
  gateway_user_service_secret:
    file: ./secrets/gateway_user_service_secret
  gateway_admin_client_secret:
    file: ./secrets/gateway_admin_client_secret
  quiz_mongo_uri:
    file: ./secrets/quiz_mongo_uri
  quiz_session_mongo_uri:
    file: ./secrets/quiz_session_mongo_uri
  quiz_session_quiz_service_url:
    file: ./secrets/quiz_session_quiz_service_url