version: '3.9'



services:
  gateway-service:
    build:
      context: ./apps/gateway-service1
    depends_on:
      - keycloak
    container_name: gateway-service
    env_file: ./apps/gateway-service1/.env
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - KEYCLOAK_CLIENT_SECRET=mjIu5pTeed0gcEfbe8Et58bf4Vo1yMHD
      - DEBUG=keycloak-connect:*
    networks:
      - wordmaster-net
      - app-net

  frontend-service:
    build:
      context: ./apps/frontend-service
      target: dev
    container_name: frontend-service
    env_file: ./apps/frontend-service/.env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./apps/frontend-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-net
      - wordmaster-net

  user-service:
    build:
      context: ./apps/user-service
    container_name: user-service
    ports:
      - "3002:3002"
    env_file: ./apps/user-service/.env
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://flapinski:cyckidupcia@postgres:5432/wordmaster
    depends_on:
      - postgres
    networks:
      - wordmaster-net
      - app-net

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: flapinski
      POSTGRES_PASSWORD: cyckidupcia
      POSTGRES_DB: wordmaster
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wordmaster-net

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: keycloakdb
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --hostname-strict=false
      - --hostname-url=http://localhost/auth
      - --hostname-admin-url=http://localhost/auth
      - --db=postgres
      - --db-url=jdbc:postgresql://keycloak-db:5432/keycloakdb
      - --db-username=keycloak
      - --db-password=securepassword
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    networks:
      - app-net
    volumes:
      - keycloak-data:/opt/keycloak/data

  redis:
    image: redis:7
    container_name: wordmaster-redis
    ports:
      - "6379:6379"
    networks:
      - wordmaster-net

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quizdb
    volumes:
      - mongo-data:/data/db
    networks:
      - wordmaster-net

  mongo-session:
    image: mongo:6
    container_name: mongo-session
    restart: always
    ports:
      - "29101:29101"
    environment:
      MONGO_INITDB_DATABASE: sessiondb
    volumes:
      - mongo-session-data:/data/db
    networks:
      - wordmaster-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
    networks:
      - app-net

  quiz-service:
    build:
      context: ./apps/quiz-service
    container_name: quiz-service
    ports:
      - "3003:3003"
    env_file: ./apps/quiz-service/.env
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo
    networks:
      - wordmaster-net
      - app-net

  quiz-session-service:
    build:
      context: ./apps/quiz-session-service
      target: dev
    container_name: quiz-session-service
    ports:
      - "3004:3004"
    env_file: ./apps/quiz-session-service/.env
    environment:
      - PORT=3004
      - MONGO_URI=mongodb://mongo-session:27017/sessiondb
    depends_on:
      - mongo-session
    volumes:
      - ./apps/quiz-session-service:/app
      - /app/node_modules
    command: npx nodemon src/index.js
    networks:
      - wordmaster-net
      - app-net

networks:
  wordmaster-net:
    driver: bridge
  app-net:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data:
  keycloak-db-data:
  user-db-data:
  mongo-data:
  mongo-session-data: