services:
  gateway-service:
    build:
      context: ./apps/gateway-service
    container_name: gateway-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - wordmaster-net
      - app-net
    depends_on:
      - keycloak
  frontend-service:
    build:
      context: ./apps/frontend-service
    container_name: frontend-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - app-net

  postgres:
    image: postgres:14
    container_name: wordmaster-postgres
    restart: always
    ports:
      - "15432:15432"
    environment:
      POSTGRES_USER: flapinski
      POSTGRES_PASSWORD: cyckidupcia
      POSTGRES_DB: wordmaster
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wordmaster-net

  redis:
    image: redis:7
    container_name: wordmaster-redis
    ports:
      - "6379:6379"
    networks:
      - wordmaster-net

networks:
  wordmaster-net:
    driver: bridge
  app-net:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data: