apiVersion: v1
data:
  frontend-nextauth-secret: c3VwZXItc2VjcmV0LXZhbHVl
kind: Secret
metadata:
  labels:
    io.kompose.service: frontend-nextauth-secret
  name: frontend-nextauth-secret
type: Opaque
