apiVersion: v1
data:
  quiz-session-mongo-uri: bW9uZ29kYjovL21vbmdvLXNlc3Npb246MjcwMTcvc2Vzc2lvbmRi
kind: Secret
metadata:
  labels:
    io.kompose.service: quiz-session-mongo-uri
  name: quiz-session-mongo-uri
type: Opaque
